// ============================================================
//  AutoVault India — Vehicle Data
// ============================================================

const VEHICLES = [
  {
    id: "tata-nexon-ev-max",
    name: "Tata Nexon EV Max",
    brand: "Tata",
    category: "suv",
    price: 19.74,
    range: 437,
    topSpeed: 120,
    charge0to80: 56,
    seats: 5,
    color: "#0ea5e9",
    badge: "Best Seller",
    image: "images/tata-nexon-ev-max.png",
    features: ["Dual Zone AC", "Panoramic Sunroof", "Ventilated Seats", "ADAS", "Connected Car Tech"],
    desc: "India's most popular electric SUV with a massive 437km range and futuristic features for the modern Indian family."
  },
  {
    id: "tata-punch-ev",
    name: "Tata Punch EV",
    brand: "Tata",
    category: "suv",
    price: 10.99,
    range: 421,
    topSpeed: 140,
    charge0to80: 56,
    seats: 5,
    color: "#22c55e",
    badge: "New Launch",
    image: "images/tata-punch-ev.png",
    features: ["7-inch Touchscreen", "Wireless Charger", "Auto Headlamps", "360° Camera", "iRA Connected"],
    desc: "Compact and mighty — the Punch EV packs a 421km range in a fun sub-compact SUV perfect for city and highways."
  },
  {
    id: "mahindra-be6e",
    name: "Mahindra BE 6e",
    brand: "Mahindra",
    category: "suv",
    price: 18.90,
    range: 682,
    topSpeed: 201,
    charge0to80: 20,
    seats: 5,
    color: "#a855f7",
    badge: "🔥 Hot",
    image: "images/mahindra-be6e.png",
    features: ["682km Range", "0-100 in 6.7s", "Fast DC Charging", "Sony Audio", "Level 2 ADAS"],
    desc: "Mahindra's flagship electric SUV breaks all barriers with 682km range and supercar-level acceleration."
  },
  {
    id: "mg-windsor-ev",
    name: "MG Windsor EV",
    brand: "MG",
    category: "sedan",
    price: 13.50,
    range: 331,
    topSpeed: 135,
    charge0to80: 55,
    seats: 5,
    color: "#f59e0b",
    badge: "Popular",
    image: "images/mg-windsor-ev.png",
    features: ["Battery-as-a-Service", "Reclining Rear Seats", "Infinity Display", "Wireless AA/CP", "One Pedal Drive"],
    desc: "Redefining value with its BaaS model — pay only for battery usage and enjoy premium features at mid-range pricing."
  },
  {
    id: "byd-seal",
    name: "BYD Seal",
    brand: "BYD",
    category: "sedan",
    price: 41.00,
    range: 650,
    topSpeed: 180,
    charge0to80: 30,
    seats: 5,
    color: "#ef4444",
    badge: "Premium",
    image: "images/byd-seal.png",
    features: ["AWD Available", "Blade Battery", "DiPilot ADAS", "Rotating Center Console", "12.8\" Rotating Screen"],
    desc: "A premium electric sedan with ocean-inspired aerodynamics and BYD's legendary Blade Battery technology."
  },
  {
    id: "hyundai-creta-ev",
    name: "Hyundai Creta EV",
    brand: "Hyundai",
    category: "suv",
    price: 17.99,
    range: 473,
    topSpeed: 160,
    charge0to80: 58,
    seats: 5,
    color: "#06b6d4",
    badge: "Top Rated",
    image: "images/hyundai-creta-ev.png",
    features: ["ADAS Level 2", "Panoramic Sunroof", "V2L Technology", "64-color Ambient Light", "OTA Updates"],
    desc: "India's most awaited electric SUV with a stunning 473km range and Hyundai's class-leading BlueLink connectivity."
  },
  {
    id: "kia-ev6",
    name: "Kia EV6",
    brand: "Kia",
    category: "luxury",
    price: 60.97,
    range: 708,
    topSpeed: 185,
    charge0to80: 18,
    seats: 5,
    color: "#8b5cf6",
    badge: "Luxury",
    image: "images/kia-ev6.png",
    features: ["800V Ultra-Fast Charging", "AWD GT-Line", "Augmented Reality HUD", "Meridian Audio", "V2L & V2G"],
    desc: "The EV6 sets a global benchmark — 800V ultra-fast charging, 708km range, and award-winning design."
  },
  {
    id: "tata-curvv-ev",
    name: "Tata Curvv EV",
    brand: "Tata",
    category: "suv",
    price: 17.49,
    range: 585,
    topSpeed: 160,
    charge0to80: 40,
    seats: 5,
    color: "#f97316",
    badge: "New",
    image: "images/tata-curvv-ev.png",
    features: ["Coupe SUV Design", "585km Range", "Digital Cockpit", "JBL Audio", "ADAS Pack"],
    desc: "India's first coupe electric SUV — striking design meets impressive 585km range in this segment-defining car."
  },
  {
    id: "ola-s1-pro",
    name: "Ola Electric S1 Pro",
    brand: "Ola",
    category: "hatchback",
    price: 1.47,
    range: 195,
    topSpeed: 123,
    charge0to80: 75,
    seats: 2,
    color: "#84cc16",
    badge: "Scooter",
    image: "images/ola-s1-pro.png",
    features: ["MoveOS 4", "Cruise Control", "Hill Hold", "Proximity Unlock", "Regen Braking"],
    desc: "India's highest-selling electric scooter — smart, stylish and packed with technology for urban commuters."
  },
  {
    id: "bmw-i4",
    name: "BMW i4 M50",
    brand: "BMW",
    category: "luxury",
    price: 93.90,
    range: 510,
    topSpeed: 225,
    charge0to80: 31,
    seats: 5,
    color: "#3b82f6",
    badge: "Ultra Luxury",
    image: "images/bmw-i4.png",
    features: ["Curved iDrive Screen", "M Sport Suspension", "Harman Kardon Audio", "BMW OS 8", "Gesture Control"],
    desc: "The BMW i4 M50 delivers 510km range with M-performance DNA — zero compromises, zero emissions."
  },
  {
    id: "mg-comet-ev",
    name: "MG Comet EV",
    brand: "MG",
    category: "hatchback",
    price: 7.98,
    range: 230,
    topSpeed: 100,
    charge0to80: 70,
    seats: 4,
    color: "#ec4899",
    badge: "City Car",
    image: "images/mg-comet-ev.png",
    features: ["Dual Screens", "Remote Control via App", "Sliding Rear Door", "360 Cam", "Smart Connect"],
    desc: "Tiny yet tech-packed — the Comet EV is built for the bustling streets of Indian metros with a funky twin-screen cockpit."
  },
  {
    id: "volvo-xc40-recharge",
    name: "Volvo XC40 Recharge",
    brand: "Volvo",
    category: "luxury",
    price: 55.90,
    range: 418,
    topSpeed: 180,
    charge0to80: 37,
    seats: 5,
    color: "#64748b",
    badge: "Safe Pick",
    image: "images/volvo-xc40-recharge.png",
    features: ["Dual Motor AWD", "Google Built-In", "Pixel LED Lights", "Bowers & Wilkins Audio", "Air Quality System"],
    desc: "Swedish luxury meets Swedish safety in the all-electric XC40 Recharge — the safest EV you can buy in India."
  },
  {
    id: "auto-gen-ev-1",
    name: "Ford Model 1 EV",
    brand: "Ford",
    category: "luxury",
    price: 16.03,
    range: 570,
    topSpeed: 136,
    charge0to80: 73,
    seats: 7,
    color: "#5043b4",
    badge: "Auto Gen",
    image: "images/tata-punch-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-2",
    name: "Toyota Model 2 EV",
    brand: "Toyota",
    category: "sedan",
    price: 19.45,
    range: 283,
    topSpeed: 126,
    charge0to80: 52,
    seats: 5,
    color: "#d95ff5",
    badge: "Auto Gen",
    image: "images/mahindra-be6e.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-3",
    name: "Ford Model 3 EV",
    brand: "Ford",
    category: "sedan",
    price: 62.71,
    range: 588,
    topSpeed: 201,
    charge0to80: 30,
    seats: 5,
    color: "#82eb54",
    badge: "Auto Gen",
    image: "images/mg-windsor-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-4",
    name: "Renault Model 4 EV",
    brand: "Renault",
    category: "suv",
    price: 52.68,
    range: 217,
    topSpeed: 124,
    charge0to80: 76,
    seats: 5,
    color: "#852569",
    badge: "Auto Gen",
    image: "images/byd-seal.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-5",
    name: "Kia Model 5 EV",
    brand: "Kia",
    category: "hatchback",
    price: 57.33,
    range: 454,
    topSpeed: 193,
    charge0to80: 76,
    seats: 5,
    color: "#2d4e74",
    badge: "Auto Gen",
    image: "images/hyundai-creta-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-6",
    name: "Renault Model 6 EV",
    brand: "Renault",
    category: "sedan",
    price: 68.66,
    range: 304,
    topSpeed: 120,
    charge0to80: 76,
    seats: 5,
    color: "#b1da6e",
    badge: "Auto Gen",
    image: "images/kia-ev6.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-7",
    name: "Mini Model 7 EV",
    brand: "Mini",
    category: "hatchback",
    price: 64.08,
    range: 324,
    topSpeed: 193,
    charge0to80: 26,
    seats: 5,
    color: "#b7091",
    badge: "Auto Gen",
    image: "images/tata-curvv-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-8",
    name: "Mercedes-Benz Model 8 EV",
    brand: "Mercedes-Benz",
    category: "luxury",
    price: 18.70,
    range: 463,
    topSpeed: 129,
    charge0to80: 73,
    seats: 5,
    color: "#fc522b",
    badge: "Auto Gen",
    image: "images/ola-s1-pro.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-9",
    name: "Peugeot Model 9 EV",
    brand: "Peugeot",
    category: "luxury",
    price: 71.65,
    range: 281,
    topSpeed: 131,
    charge0to80: 27,
    seats: 7,
    color: "#6a3166",
    badge: "Auto Gen",
    image: "images/bmw-i4.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-10",
    name: "Honda Model 10 EV",
    brand: "Honda",
    category: "hatchback",
    price: 74.23,
    range: 428,
    topSpeed: 125,
    charge0to80: 77,
    seats: 5,
    color: "#18744",
    badge: "Auto Gen",
    image: "images/mg-comet-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-11",
    name: "Toyota Model 11 EV",
    brand: "Toyota",
    category: "hatchback",
    price: 28.73,
    range: 573,
    topSpeed: 177,
    charge0to80: 33,
    seats: 7,
    color: "#85e052",
    badge: "Auto Gen",
    image: "images/volvo-xc40-recharge.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-12",
    name: "Mercedes-Benz Model 12 EV",
    brand: "Mercedes-Benz",
    category: "luxury",
    price: 56.96,
    range: 480,
    topSpeed: 146,
    charge0to80: 21,
    seats: 5,
    color: "#a36313",
    badge: "Auto Gen",
    image: "images/tata-nexon-ev-max.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-13",
    name: "Mercedes-Benz Model 13 EV",
    brand: "Mercedes-Benz",
    category: "hatchback",
    price: 87.12,
    range: 200,
    topSpeed: 209,
    charge0to80: 29,
    seats: 7,
    color: "#fad655",
    badge: "Auto Gen",
    image: "images/tata-punch-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-14",
    name: "Rivian Model 14 EV",
    brand: "Rivian",
    category: "luxury",
    price: 46.28,
    range: 532,
    topSpeed: 126,
    charge0to80: 49,
    seats: 5,
    color: "#5b22b3",
    badge: "Auto Gen",
    image: "images/mahindra-be6e.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-15",
    name: "BMW Model 15 EV",
    brand: "BMW",
    category: "suv",
    price: 42.29,
    range: 556,
    topSpeed: 214,
    charge0to80: 73,
    seats: 7,
    color: "#c0e1d8",
    badge: "Auto Gen",
    image: "images/mg-windsor-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-16",
    name: "Hyundai Model 16 EV",
    brand: "Hyundai",
    category: "suv",
    price: 84.74,
    range: 294,
    topSpeed: 190,
    charge0to80: 48,
    seats: 5,
    color: "#813cd4",
    badge: "Auto Gen",
    image: "images/byd-seal.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-17",
    name: "Volvo Model 17 EV",
    brand: "Volvo",
    category: "luxury",
    price: 45.49,
    range: 422,
    topSpeed: 210,
    charge0to80: 32,
    seats: 7,
    color: "#c024a9",
    badge: "Auto Gen",
    image: "images/hyundai-creta-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-18",
    name: "Tesla Model 18 EV",
    brand: "Tesla",
    category: "hatchback",
    price: 37.39,
    range: 441,
    topSpeed: 182,
    charge0to80: 51,
    seats: 5,
    color: "#891573",
    badge: "Auto Gen",
    image: "images/kia-ev6.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-19",
    name: "Mini Model 19 EV",
    brand: "Mini",
    category: "hatchback",
    price: 73.65,
    range: 376,
    topSpeed: 177,
    charge0to80: 73,
    seats: 5,
    color: "#78ded1",
    badge: "Auto Gen",
    image: "images/tata-curvv-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-20",
    name: "Volkswagen Model 20 EV",
    brand: "Volkswagen",
    category: "sedan",
    price: 25.69,
    range: 378,
    topSpeed: 137,
    charge0to80: 77,
    seats: 7,
    color: "#2f5d9f",
    badge: "Auto Gen",
    image: "images/ola-s1-pro.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-21",
    name: "Honda Model 21 EV",
    brand: "Honda",
    category: "luxury",
    price: 79.74,
    range: 486,
    topSpeed: 161,
    charge0to80: 53,
    seats: 5,
    color: "#9fe27",
    badge: "Auto Gen",
    image: "images/bmw-i4.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-22",
    name: "Ford Model 22 EV",
    brand: "Ford",
    category: "hatchback",
    price: 82.04,
    range: 528,
    topSpeed: 164,
    charge0to80: 32,
    seats: 5,
    color: "#68d0b9",
    badge: "Auto Gen",
    image: "images/mg-comet-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-23",
    name: "Lucid Model 23 EV",
    brand: "Lucid",
    category: "luxury",
    price: 10.64,
    range: 208,
    topSpeed: 151,
    charge0to80: 76,
    seats: 7,
    color: "#f78916",
    badge: "Auto Gen",
    image: "images/volvo-xc40-recharge.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-24",
    name: "Hyundai Model 24 EV",
    brand: "Hyundai",
    category: "luxury",
    price: 23.43,
    range: 251,
    topSpeed: 216,
    charge0to80: 75,
    seats: 5,
    color: "#f104c9",
    badge: "Auto Gen",
    image: "images/tata-nexon-ev-max.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-25",
    name: "Kia Model 25 EV",
    brand: "Kia",
    category: "luxury",
    price: 76.94,
    range: 284,
    topSpeed: 170,
    charge0to80: 21,
    seats: 5,
    color: "#3133cf",
    badge: "Auto Gen",
    image: "images/tata-punch-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-26",
    name: "Volkswagen Model 26 EV",
    brand: "Volkswagen",
    category: "sedan",
    price: 77.42,
    range: 415,
    topSpeed: 185,
    charge0to80: 41,
    seats: 5,
    color: "#b15e06",
    badge: "Auto Gen",
    image: "images/mahindra-be6e.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-27",
    name: "Renault Model 27 EV",
    brand: "Renault",
    category: "sedan",
    price: 23.45,
    range: 353,
    topSpeed: 184,
    charge0to80: 66,
    seats: 5,
    color: "#52acda",
    badge: "Auto Gen",
    image: "images/mg-windsor-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-28",
    name: "Hyundai Model 28 EV",
    brand: "Hyundai",
    category: "hatchback",
    price: 16.45,
    range: 376,
    topSpeed: 201,
    charge0to80: 68,
    seats: 5,
    color: "#cc59b1",
    badge: "Auto Gen",
    image: "images/byd-seal.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-29",
    name: "Kia Model 29 EV",
    brand: "Kia",
    category: "hatchback",
    price: 83.05,
    range: 505,
    topSpeed: 161,
    charge0to80: 20,
    seats: 5,
    color: "#223d1b",
    badge: "Auto Gen",
    image: "images/hyundai-creta-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-30",
    name: "Mercedes-Benz Model 30 EV",
    brand: "Mercedes-Benz",
    category: "suv",
    price: 57.45,
    range: 231,
    topSpeed: 133,
    charge0to80: 41,
    seats: 5,
    color: "#acf7e6",
    badge: "Auto Gen",
    image: "images/kia-ev6.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-31",
    name: "Tesla Model 31 EV",
    brand: "Tesla",
    category: "luxury",
    price: 13.33,
    range: 534,
    topSpeed: 146,
    charge0to80: 79,
    seats: 7,
    color: "#f66dc4",
    badge: "Auto Gen",
    image: "images/tata-curvv-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-32",
    name: "Audi Model 32 EV",
    brand: "Audi",
    category: "suv",
    price: 29.03,
    range: 492,
    topSpeed: 175,
    charge0to80: 52,
    seats: 5,
    color: "#b995bd",
    badge: "Auto Gen",
    image: "images/ola-s1-pro.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-33",
    name: "Nissan Model 33 EV",
    brand: "Nissan",
    category: "suv",
    price: 73.48,
    range: 530,
    topSpeed: 172,
    charge0to80: 62,
    seats: 7,
    color: "#a6c351",
    badge: "Auto Gen",
    image: "images/bmw-i4.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-34",
    name: "Nissan Model 34 EV",
    brand: "Nissan",
    category: "sedan",
    price: 68.01,
    range: 359,
    topSpeed: 189,
    charge0to80: 22,
    seats: 5,
    color: "#471f63",
    badge: "Auto Gen",
    image: "images/mg-comet-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-35",
    name: "Chevrolet Model 35 EV",
    brand: "Chevrolet",
    category: "hatchback",
    price: 14.93,
    range: 352,
    topSpeed: 218,
    charge0to80: 63,
    seats: 5,
    color: "#299ed4",
    badge: "Auto Gen",
    image: "images/volvo-xc40-recharge.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-36",
    name: "Ford Model 36 EV",
    brand: "Ford",
    category: "sedan",
    price: 38.03,
    range: 391,
    topSpeed: 150,
    charge0to80: 51,
    seats: 5,
    color: "#7b0cf6",
    badge: "Auto Gen",
    image: "images/tata-nexon-ev-max.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-37",
    name: "Volvo Model 37 EV",
    brand: "Volvo",
    category: "hatchback",
    price: 73.20,
    range: 508,
    topSpeed: 179,
    charge0to80: 27,
    seats: 5,
    color: "#63dd2f",
    badge: "Auto Gen",
    image: "images/tata-punch-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-38",
    name: "Volvo Model 38 EV",
    brand: "Volvo",
    category: "luxury",
    price: 59.45,
    range: 210,
    topSpeed: 145,
    charge0to80: 45,
    seats: 5,
    color: "#c3a617",
    badge: "Auto Gen",
    image: "images/mahindra-be6e.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-39",
    name: "Polestar Model 39 EV",
    brand: "Polestar",
    category: "hatchback",
    price: 48.19,
    range: 489,
    topSpeed: 173,
    charge0to80: 29,
    seats: 5,
    color: "#f8737a",
    badge: "Auto Gen",
    image: "images/mg-windsor-ev.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  },
  {
    id: "auto-gen-ev-40",
    name: "Tesla Model 40 EV",
    brand: "Tesla",
    category: "sedan",
    price: 23.59,
    range: 226,
    topSpeed: 146,
    charge0to80: 66,
    seats: 5,
    color: "#49f622",
    badge: "Auto Gen",
    image: "images/byd-seal.png",
    features: ["Feature A", "Feature B", "Feature C", "Feature D", "Feature E"],
    desc: "A powerful and efficient electric vehicle generated for testing purposes."
  }
];
