// ============================================================
//  AutoVault India — Vehicle Data
// ============================================================

const VEHICLES = [
  {
    id: "tata-nexon-ev-max",
    name: "Tata Nexon EV Max",
    brand: "Tata",
    category: "suv",
    price: 19.74,
    range: 437,
    topSpeed: 120,
    charge0to80: 56,
    seats: 5,
    color: "#0ea5e9",
    badge: "Best Seller",
    image: "https://www.motortrend.com/uploads/2023/01/2023-Tata-Nexon-EV-Max-front-three-quarter-in-motion-3.jpg",
    features: ["Dual Zone AC", "Panoramic Sunroof", "Ventilated Seats", "ADAS", "Connected Car Tech"],
    desc: "India's most popular electric SUV with a massive 437km range and futuristic features for the modern Indian family."
  },
  {
    id: "tata-punch-ev",
    name: "Tata Punch EV",
    brand: "Tata",
    category: "suv",
    price: 10.99,
    range: 421,
    topSpeed: 140,
    charge0to80: 56,
    seats: 5,
    color: "#22c55e",
    badge: "New Launch",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Tata_Punch_EV_at_Bharat_Mobility_2024.jpg/1280px-Tata_Punch_EV_at_Bharat_Mobility_2024.jpg",
    features: ["7-inch Touchscreen", "Wireless Charger", "Auto Headlamps", "360° Camera", "iRA Connected"],
    desc: "Compact and mighty — the Punch EV packs a 421km range in a fun sub-compact SUV perfect for city and highways."
  },
  {
    id: "mahindra-be6e",
    name: "Mahindra BE 6e",
    brand: "Mahindra",
    category: "suv",
    price: 18.90,
    range: 682,
    topSpeed: 201,
    charge0to80: 20,
    seats: 5,
    color: "#a855f7",
    badge: "🔥 Hot",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Mahindra_BE.6e_at_Bharat_Mobility_Global_Expo_2025_%28cropped%29.jpg/1280px-Mahindra_BE.6e_at_Bharat_Mobility_Global_Expo_2025_%28cropped%29.jpg",
    features: ["682km Range", "0-100 in 6.7s", "Fast DC Charging", "Sony Audio", "Level 2 ADAS"],
    desc: "Mahindra's flagship electric SUV breaks all barriers with 682km range and supercar-level acceleration."
  },
  {
    id: "mg-windsor-ev",
    name: "MG Windsor EV",
    brand: "MG",
    category: "sedan",
    price: 13.50,
    range: 331,
    topSpeed: 135,
    charge0to80: 55,
    seats: 5,
    color: "#f59e0b",
    badge: "Popular",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/MG_Windsor_EV_at_Bharat_Mobility_2025.jpg/1280px-MG_Windsor_EV_at_Bharat_Mobility_2025.jpg",
    features: ["Battery-as-a-Service", "Reclining Rear Seats", "Infinity Display", "Wireless AA/CP", "One Pedal Drive"],
    desc: "Redefining value with its BaaS model — pay only for battery usage and enjoy premium features at mid-range pricing."
  },
  {
    id: "byd-seal",
    name: "BYD Seal",
    brand: "BYD",
    category: "sedan",
    price: 41.00,
    range: 650,
    topSpeed: 180,
    charge0to80: 30,
    seats: 5,
    color: "#ef4444",
    badge: "Premium",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/BYD_Seal_at_the_2022_Paris_Motor_Show.jpg/1280px-BYD_Seal_at_the_2022_Paris_Motor_Show.jpg",
    features: ["AWD Available", "Blade Battery", "DiPilot ADAS", "Rotating Center Console", "12.8\" Rotating Screen"],
    desc: "A premium electric sedan with ocean-inspired aerodynamics and BYD's legendary Blade Battery technology."
  },
  {
    id: "hyundai-creta-ev",
    name: "Hyundai Creta EV",
    brand: "Hyundai",
    category: "suv",
    price: 17.99,
    range: 473,
    topSpeed: 160,
    charge0to80: 58,
    seats: 5,
    color: "#06b6d4",
    badge: "Top Rated",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Hyundai_Creta_Electric_at_Bharat_Mobility_2024.jpg/1280px-Hyundai_Creta_Electric_at_Bharat_Mobility_2024.jpg",
    features: ["ADAS Level 2", "Panoramic Sunroof", "V2L Technology", "64-color Ambient Light", "OTA Updates"],
    desc: "India's most awaited electric SUV with a stunning 473km range and Hyundai's class-leading BlueLink connectivity."
  },
  {
    id: "kia-ev6",
    name: "Kia EV6",
    brand: "Kia",
    category: "luxury",
    price: 60.97,
    range: 708,
    topSpeed: 185,
    charge0to80: 18,
    seats: 5,
    color: "#8b5cf6",
    badge: "Luxury",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Kia_EV6_GT-Line_%28facelift%2C_first_gen%29%2C_front_8.4.23.jpg/1280px-Kia_EV6_GT-Line_%28facelift%2C_first_gen%29%2C_front_8.4.23.jpg",
    features: ["800V Ultra-Fast Charging", "AWD GT-Line", "Augmented Reality HUD", "Meridian Audio", "V2L & V2G"],
    desc: "The EV6 sets a global benchmark — 800V ultra-fast charging, 708km range, and award-winning design."
  },
  {
    id: "tata-curvv-ev",
    name: "Tata Curvv EV",
    brand: "Tata",
    category: "suv",
    price: 17.49,
    range: 585,
    topSpeed: 160,
    charge0to80: 40,
    seats: 5,
    color: "#f97316",
    badge: "New",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Tata_Curvv_EV_front_left.jpg/1280px-Tata_Curvv_EV_front_left.jpg",
    features: ["Coupe SUV Design", "585km Range", "Digital Cockpit", "JBL Audio", "ADAS Pack"],
    desc: "India's first coupe electric SUV — striking design meets impressive 585km range in this segment-defining car."
  },
  {
    id: "ola-s1-pro",
    name: "Ola Electric S1 Pro",
    brand: "Ola",
    category: "hatchback",
    price: 1.47,
    range: 195,
    topSpeed: 123,
    charge0to80: 75,
    seats: 2,
    color: "#84cc16",
    badge: "Scooter",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Ola_S1_Pro.jpg/1280px-Ola_S1_Pro.jpg",
    features: ["MoveOS 4", "Cruise Control", "Hill Hold", "Proximity Unlock", "Regen Braking"],
    desc: "India's highest-selling electric scooter — smart, stylish and packed with technology for urban commuters."
  },
  {
    id: "bmw-i4",
    name: "BMW i4 M50",
    brand: "BMW",
    category: "luxury",
    price: 93.90,
    range: 510,
    topSpeed: 225,
    charge0to80: 31,
    seats: 5,
    color: "#3b82f6",
    badge: "Ultra Luxury",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/BMW_i4_M50_IAA_2021_1X7A0175.jpg/1280px-BMW_i4_M50_IAA_2021_1X7A0175.jpg",
    features: ["Curved iDrive Screen", "M Sport Suspension", "Harman Kardon Audio", "BMW OS 8", "Gesture Control"],
    desc: "The BMW i4 M50 delivers 510km range with M-performance DNA — zero compromises, zero emissions."
  },
  {
    id: "mg-comet-ev",
    name: "MG Comet EV",
    brand: "MG",
    category: "hatchback",
    price: 7.98,
    range: 230,
    topSpeed: 100,
    charge0to80: 70,
    seats: 4,
    color: "#ec4899",
    badge: "City Car",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/MG_Comet_EV.jpg/1280px-MG_Comet_EV.jpg",
    features: ["Dual Screens", "Remote Control via App", "Sliding Rear Door", "360 Cam", "Smart Connect"],
    desc: "Tiny yet tech-packed — the Comet EV is built for the bustling streets of Indian metros with a funky twin-screen cockpit."
  },
  {
    id: "volvo-xc40-recharge",
    name: "Volvo XC40 Recharge",
    brand: "Volvo",
    category: "luxury",
    price: 55.90,
    range: 418,
    topSpeed: 180,
    charge0to80: 37,
    seats: 5,
    color: "#64748b",
    badge: "Safe Pick",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/2021_Volvo_XC40_Recharge_P8_AWD_%28facelift%2C_Glacier_Silver%29%2C_front_8.21.21.jpg/1280px-2021_Volvo_XC40_Recharge_P8_AWD_%28facelift%2C_Glacier_Silver%29%2C_front_8.21.21.jpg",
    features: ["Dual Motor AWD", "Google Built-In", "Pixel LED Lights", "Bowers & Wilkins Audio", "Air Quality System"],
    desc: "Swedish luxury meets Swedish safety in the all-electric XC40 Recharge — the safest EV you can buy in India."
  }
];
